# Generated by Django 4.1.1 on 2022-10-02 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('service_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_issued', models.DateField(verbose_name='Date Published')),
                ('included_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.service')),
            ],
        ),
    ]
