# Generated by Django 4.1.1 on 2022-10-02 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_issued']},
        ),
        migrations.AddField(
            model_name='service',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='included_services',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Enter the product name', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Enter the service name', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='included_services',
            field=models.ManyToManyField(help_text='Select the services for this product', to='products.service'),
        ),
    ]
