# Generated by Django 4.1.1 on 2022-10-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_service_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='author',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, help_text='This will be auto generated', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.FloatField(default=0),
        ),
    ]
